trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# First set BUILDOPTS as a environment wide variable
- script: "echo \"##vso[task.setvariable variable=BUILDOPTS]-j$(nproc) VERBOSE=1 FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1\""
- script: make check-whitespace
- bash: |
    contrib/travis_fastfail.sh || exit 1;
    sudo apt-get update
    sudo apt-get install -y ccache gfortran
    contrib/download_cmake.sh
  displayName: setup
- script: |
    make $BUILDOPTS -C base version_git.jl.phony
    make $BUILDOPTS NO_GIT=1 -C deps
  displayName: dependencies
  env:
    BUILDOPTS: $(BUILDOPTS)
- script: |
    make $BUILDOPTS NO_GIT=1 prefix=/tmp/julia release
  displayName: release
  env:
    BUILDOPTS: $(BUILDOPTS)
- script: |
    make $BUILDOPTS NO_GIT=1 prefix=/tmp/julia debug
  displayName: debug
  env:
    BUILDOPTS: $(BUILDOPTS)
