trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables: 
  BUILDOPTS: "FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1"

jobs:
- job: dependencies
  steps:
  - bash: |
      make check-whitespace
      contrib/travis_fastfail.sh || exit 1;
      sudo apt-get update
      sudo apt-get install -y gfortran
      contrib/download_cmake.sh
    displayName: setup
  - bash: |
      make -j $BUILDOPTS NO_GIT=1 -C deps
    displayName: dependencies
    env:
      BUILDOPTS: $(BUILDOPTS)
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'dependencies'
      targetPath: 'usr'

- job: release
  dependsOn: dependencies
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)
  - bash: |
      make $BUILDOPTS -C base version_git.jl.phony
      make -j $BUILDOPTS NO_GIT=1 prefix=/tmp/julia release
    env:
      BUILDOPTS: $(BUILDOPTS)

